// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.startupExperimentPrefs.network.http.spdy.websockets", false);
user_pref("app.normandy.user_id", "829c9b1b-ef49-478d-91d7-1e5d828417eb");
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1562667275);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1563507045);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1563507285);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1563507525);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1563507405);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 1563507645);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1563507765);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1563507165);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 1048576);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.download.panel.shown", true);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1561108156);
user_pref("browser.laterrun.bookkeeping.sessionCount", 11);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 77);
user_pref("browser.newtabpage.activity-stream.impressionId", "{06c38060-aae5-4ec0-9700-1f8a99b6f63b}");
user_pref("browser.newtabpage.activity-stream.migrationExpired", true);
user_pref("browser.newtabpage.activity-stream.migrationLastShownDate", 1561050000);
user_pref("browser.newtabpage.activity-stream.migrationRemainingDays", 3);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"addSearchEngine\",\"sendToDevice\",\"pocket\",\"screenshots_mozilla_org\"],\"idsInUrlbar\":[\"pocket\",\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.safebrowsing.provider.google4.lastupdatetime", "1563518083819");
user_pref("browser.safebrowsing.provider.google4.nextupdatetime", "1563519879819");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1563532224308");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1563535824308");
user_pref("browser.search.region", "VN");
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20190128144255");
user_pref("browser.shell.mostRecentDateSetAsDefault", "1563532216");
user_pref("browser.slowStartup.averageTime", 1263);
user_pref("browser.slowStartup.samples", 1);
user_pref("browser.startup.homepage_override.buildID", "20190128144255");
user_pref("browser.startup.homepage_override.mstone", "65.0");
user_pref("browser.tabs.warnOnClose", false);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"library-button\",\"sidebar-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"personal-bookmarks\"]},\"seen\":[\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\",\"toolbar-menubar\",\"TabsToolbar\",\"PersonalToolbar\"],\"currentVersion\":15,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("browser.urlbar.timesBeforeHidingSuggestionsHint", 0);
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1561108159368");
user_pref("devtools.onboarding.telemetry.logged", true);
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "65.0");
user_pref("distribution.iniFile.exists.value", true);
user_pref("dom.push.userAgentID", "793183141488408c9b7288fc5adae5c4");
user_pref("extensions.blocklist.lastModified", "Wed, 17 Jul 2019 12:38:35 GMT");
user_pref("extensions.blocklist.pingCountTotal", 3);
user_pref("extensions.blocklist.pingCountVersion", 3);
user_pref("extensions.databaseSchema", 28);
user_pref("extensions.getAddons.cache.lastUpdate", 1562667282);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.lastAppBuildId", "20190128144255");
user_pref("extensions.lastAppVersion", "65.0");
user_pref("extensions.lastPlatformVersion", "65.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.uuids", "{\"formautofill@mozilla.org\":\"7e2db847-c53a-45aa-ab8c-1f0bdb78023f\",\"screenshots@mozilla.org\":\"aa630d41-6be4-4e38-9333-4fc5f908cebc\",\"webcompat-reporter@mozilla.org\":\"87bbeae6-e05f-47ef-a5b6-0248aa809c19\",\"webcompat@mozilla.org\":\"9691de77-bd13-43b7-a19a-fda823619d8f\",\"baidu-code-update@mozillaonline.com\":\"5b7c61d1-0bc9-4bff-bbf8-59f6338bb097\",\"fxmonitor@mozilla.org\":\"82b2a95a-c184-402e-ba44-ad30ac865b87\"}");
user_pref("idle.lastDailyNotification", 1563508881);
user_pref("lightweightThemes.usedThemes", "[]");
user_pref("media.benchmark.vp9.fps", 123);
user_pref("media.benchmark.vp9.versioncheck", 5);
user_pref("media.gmp-gmpopenh264.abi", "x86_64-gcc3");
user_pref("media.gmp-gmpopenh264.lastUpdate", 1563507368);
user_pref("media.gmp-gmpopenh264.version", "1.7.1");
user_pref("media.gmp-manager.buildID", "20190128144255");
user_pref("media.gmp-manager.lastCheck", 1563507368);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.predictor.cleaned-up", true);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.database.lastMaintenance", 1563508881);
user_pref("places.history.expiration.transient_current_max_pages", 112348);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("privacy.sanitize.pending", "[]");
user_pref("security.sandbox.content.tempDirSuffix", "7a0cbd70-80b4-4bd5-9e5d-2637812c39ce");
user_pref("security.sandbox.plugin.tempDirSuffix", "17fef06e-cda9-4440-b488-347160b00089");
user_pref("services.blocklist.addons.checked", 1563507050);
user_pref("services.blocklist.gfx.checked", 1563507050);
user_pref("services.blocklist.onecrl.checked", 1563507050);
user_pref("services.blocklist.pinning.checked", 1563507050);
user_pref("services.blocklist.plugins.checked", 1563507050);
user_pref("services.settings.clock_skew_seconds", -99);
user_pref("services.settings.last_update_seconds", 1563507744);
user_pref("services.settings.main.language-dictionaries.last_check", 1563507050);
user_pref("services.settings.main.onboarding.last_check", 1563507050);
user_pref("services.settings.main.sites-classification.last_check", 1563507050);
user_pref("signon.importedFromSqlite", true);
user_pref("storage.vacuum.last.index", 0);
user_pref("storage.vacuum.last.places.sqlite", 1563508881);
user_pref("toolkit.startup.last_success", 1563518076);
user_pref("toolkit.telemetry.cachedClientID", "54f89803-0a3f-46ac-b6a4-1a4c67082145");
user_pref("toolkit.telemetry.previousBuildID", "20190128144255");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
